### ISSUE TITLE
Build from the command line using ant.

### ISSUE THREAD

**Issue by menzow** [nccgroup/BurpSuiteHTTPSmuggler#4]
After checking out the repo I wasn't able to use ant to compile the code into a jar file. After noticing that the build.xml file doesn't appear to be used I made the file compatible with ant. 

For this I opened the following PR: https://github.com/nccgroup/BurpSuiteHTTPSmuggler/pull/3. Not sure if a issue is required when submitting a PR, but here it is anyway. ;)

**Comment by irsdl** [comment]
I think I have applied this now. If there is any issues, please let me know.
