### ISSUE TITLE
How to use this extension ?

### ISSUE THREAD

**Issue by lowk3v** [nccgroup/BurpSuiteHTTPSmuggler#5]
Can you provide guideline for use? It have many options in Encoding tab, I don't understandg it.

**Comment by irsdl** [comment]
That’s why I have defined policies. If the encoding does not work for you when changing the policy, and you have read https://www.nccgroup.trust/uk/about-us/newsroom-and-events/blogs/2017/august/request-encoding-to-bypass-web-application-firewalls/ already, please include your target web server here and perhaps we can have a look at it in the future to add a new policy :)

You need to have a good understanding of the webserver if you want to change the options manually.
