### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by shadowzoom** [nccgroup/BurpSuiteHTTPSmuggler#6]
Hi there! I've looked in every folder but didn't find a jar file. How i can install this app to my Burp?

**Comment by irsdl** [comment]
It's here:
![image](https://user-images.githubusercontent.com/1798313/43348415-c93ed0d2-91f1-11e8-9056-522e2edc50c3.png)

https://github.com/nccgroup/BurpSuiteHTTPSmuggler/releases
